### ISSUE TITLE
About this release

### ISSUE THREAD

**Issue by jhabdas** [jasnell/node#11]
This is an _pending_ LTS release candidate with tentative support [promised](https://github.com/nodejs/LTS#lts-schedule1) until the end of 2019.

When upgrading, please be aware of the following draft EPS:
https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md

**Comment by jasnell** [comment]
Not sure why this comment is left here. This is my personal development fork. Comments relating to the node project should be left on the main repo.

**Comment by jhabdas** [comment]
Check your graphs, bro.
