### ISSUE TITLE
Dear @jasnell about inclusivity repository

### ISSUE THREAD

**Issue by dangerrust** [jasnell/node#2]
Dear @jasnell 

Sorry for the to misunderstanding. I was concerned by a comment by another user featuring a purple vegetable emoji representing abbreviation 'coc'. I will not go into too much detail but I will reproduce it here for reference: 🍆 purple vegetable emoji. I decided, it was inappropriate if code of conduct was abbreviated to a word that would lead to these kinds of posting 'jokes'.

I am sorry for posting this in the repository, but GitHub did not allow me to post this on the inclusive repository.

Thank you for understanding,
N. Petrescu

**Comment by jasnell** [comment]
@dangerrust ... I appreciate the apology and will pass it on.

**Comment by dangerrust** [comment]
Thank you @jasnell and please let them know that I have found Node fantastic and fully support all efforts to expand the diversity of Node.js contributors. If Node is fantastic with only a small minority of the 50% of women in the world contributing, it could be nearly twice as good if the obstacles were extirpated and participation made full.
